name: Repose
options:
  bundleIdPrefix: com.repose
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.9.0"

targets:
  Repose:
    type: application
    platform: macOS
    sources:
      - Repose
    dependencies:
      - package: Sparkle
    settings:
      base:
        INFOPLIST_FILE: Repose/Info.plist
        CODE_SIGN_ENTITLEMENTS: Repose/Repose.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.repose.app
        MARKETING_VERSION: "1.1.0"
        CURRENT_PROJECT_VERSION: "2"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: FBS8R927D4
        ENABLE_HARDENED_RUNTIME: YES
